version: '2'
services:
  webserver:
    image: slidewiki/webproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-trier
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ../htpasswd:/etc/nginx/htpasswd # Not tracked as part of this repo

  platform:
    #image: slidewiki/platform
    build: ~/slidewiki/slidewiki-platform
    expose:
      - "80"
    environment:
      - PORT=80
      - SERVICE_URL_DECK=https://deckservice.slidewiki.org
      - SERVICE_URL_DISCUSSION=https://discussionservice.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.slidewiki.org
      - SERVICE_URL_NOTIFICATION=https://notificationservice.slidewiki.org
      - SERVICE_URL_USER=https://userservice.slidewiki.org
      - SERVICE_URL_IMPORT=https://importservice.slidewiki.org
      - SERVICE_URL_FILE=https://fileservice.slidewiki.org
      - SERVICE_URL_SEARCH=https://searchservice.slidewiki.org
      - SERVICE_URL_IMAGE=https://imageservice.slidewiki.org
      - SERVICE_URL_PDF=https://pdfservice.slidewiki.org
      - SERVICE_VAR_IMPORT_HOST=importservice.slidewiki.org
    networks:
      - front-trier
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - imageservice

  deckservice:
    build: ~/slidewiki/deck-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_FILE=https://fileservice.slidewiki.org
      - SERVICE_URL_IMAGE=https://imageservice.slidewiki.org
    depends_on:
      - fileservice
#      - imageservice
      - mongodb

  activitiesservice:
    build: ~/slidewiki/activities-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.slidewiki.org
      - SERVICE_URL_USER=https://userservice.slidewiki.org
    depends_on:
      - deckservice
      - userservice
      - mongodb

  discussionservice:
    build: ~/slidewiki/discussion-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.slidewiki.org
      - SERVICE_URL_NOTIFICATION=https://notificationservice.slidewiki.org
      - SERVICE_URL_USER=https://userservice.slidewiki.org
    depends_on:
      - activitiesservice
      - notificationservice
      - userservice
      - mongodb

  notificationservice:
    build: ~/slidewiki/notification-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_USER=https://userservice.slidewiki.org
    depends_on:
      - userservice
      - mongodb

  importservice:
    build: ~/slidewiki/import-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.slidewiki.org
      - SERVICE_URL_FILE=https://fileservice.slidewiki.org
    depends_on:
      - deckservice
      - fileservice
      - mongodb

  imageservice:
    build: ~/slidewiki/image-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_FILE=https://fileservice.slidewiki.org
    depends_on:
      - importservice
      - fileservice
      - mongodb

  userservice:
    build: ~/slidewiki/user-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SMTP_PORT=25
      - SMTP_HOST=localhost
  #    - SMTP_FROM=me@hostername.org
  #    - SMTP_CLIENTNAME=
  #    - APIKey=
      - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
      - URL_PLATFORM=https://slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.slidewiki.org
    volumes:
      - /data/userservice/providerConfig_json:/nodeApp/config.json
    depends_on:
  #    - platform
  #    - activitiesservice
      - mongodb

  pdfservice:
    build: ~/slidewiki/PDF-Service
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - SERVICE_URL_DECK=https://deckservice.slidewiki.org
      - SERVICE_URL_PDF=https://pdfservice.slidewiki.org
      - SERVICE_URL_PLATFORM=https://slidewiki.org
    depends_on:
      - deckservice

  fileservice:
    build: ~/slidewiki/file-service
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  searchservice:
    build: ~/slidewiki/search-service
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SERVICE_URL_DECK=https://deckservice.slidewiki.org
      - SERVICE_URL_USER=https://userservice.slidewiki.org
      - SOLR_HOST=solr
    depends_on:
      - userservice
      - solr
      - mongodb

  solr:
    image: solr
    container_name: solr
    expose:
      - "8983"
    networks:
      - back-trier
    depends_on:
      - mongodb

  #xapi:
  #  image: slidewiki/xapi-service
  #  expose:
  #    - "80"
  #  networks:
  #    - front-trier
  #  environment:
  #    - APPLICATION_PORT=80

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
        - "27017"
    networks:
      - back-trier
    volumes:
      - database:/data/db
    command: mongod --replSet "rs0"

networks:
  front-trier: {}
  back-trier: {}
