version: '2'
services:
  webserver:
    restart: always

  platform:
    restart: always
    environment:
      - VIRTUAL_HOST=platform.localhost
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_DISCUSSION=http://discussionservice
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
      - SERVICE_URL_NOTIFICATION=http://notificationservice
      - SERVICE_URL_USER=http://userservice
      - SERVICE_URL_IMPORT=http://importservice
      - SERVICE_URL_FILE=http://fileservice
      - SERVICE_URL_SEARCH=http://searchservice
      - SERVICE_URL_IMAGE=http://imageservice
      - SERVICE_URL_PDF=http://pdfservice
      - SERVICE_VAR_IMPORT_HOST=importservice
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - imageservice

  deckservice:
    restart: always
    environment:
      - VIRTUAL_HOST=deckservice.localhost
      - SERVICE_URL_FILE=fileservice
      - SERVICE_URL_IMAGE=imageservice
    depends_on:
      - fileservice
#      - imageservice
      - mongodb

  activitiesservice:
    restart: always
    environment:
      - VIRTUAL_HOST=activitiesservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_USER=userservice
    depends_on:
      - deckservice
      - userservice
      - mongodb

  discussionservice:
    restart: always
    environment:
      - VIRTUAL_HOST=discussionservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_ACTIVITIES=activitiesservice
      - SERVICE_URL_NOTIFICATION=notificationservice
      - SERVICE_URL_USER=userservice
    depends_on:
      - activitiesservice
      - notificationservice
      - userservice
      - mongodb

  notificationservice:
    restart: always
    environment:
      - VIRTUAL_HOST=notificationservice.localhost
      - SERVICE_URL_USER=userservice
    depends_on:
      - userservice
      - mongodb

  importservice:
    restart: always
    environment:
      - VIRTUAL_HOST=importservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_FILE=fileservice
    volumes:
      - ./images:/data/files
    depends_on:
      - deckservice
      - fileservice
      - mongodb

  imageservice:
    restart: always
    environment:
      - VIRTUAL_HOST=imageservice.localhost
      - SERVICE_URL_FILE=fileservice
    volumes:
      - ./images:/data/files
    depends_on:
      - importservice
      - fileservice
      - mongodb

  userservice:
    restart: always
    environment:
      - VIRTUAL_HOST=userservice
    depends_on:
      - mongodb

  pdfservice:
    restart: always
    environment:
      - VIRTUAL_HOST=pdfservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_PDF=pdfservice
      - SERVICE_URL_PLATFORM=platform
    depends_on:
      - deckservice
#      - platform

  fileservice:
    restart: always
    environment:
      - VIRTUAL_HOST=fileservice.localhost
    volumes:
      - ./images:/data/files
    depends_on:
      - mongodb

  searchservice:
    restart: always
    environment:
      - VIRTUAL_HOST=searchservice.localhost
      - SERVICE_URL_USER=userservice
    depends_on:
      - userservice
      - solr
      - mongodb

  solr:
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ../solrserver-config/solr-config:/opt/solr/server/solr
      - ../solrserver-config/solr-data:/solr-data
    depends_on:
      - mongodb

  mongodb:
    restart: always
    volumes:
      - ./database:/data/db
      - ../solrserver-config/solr-data:/solr-data # needed by prepare script. Do not change it to solr as solr-data must have the correct rights before solr is started
