version: '2'
services:
  webserver:
    restart: always
    environment:
      - BASENAME=localhost

  platform:
    restart: always
    environment:
      - VIRTUAL_HOST=platform.localhost

  deckservice:
    restart: always
    environment:
      - VIRTUAL_HOST=deckservice.localhost

  activitiesservice:
    restart: always
    environment:
      - VIRTUAL_HOST=activitiesservice.localhost

  discussionservice:
    restart: always
    environment:
      - VIRTUAL_HOST=discussionservice.localhost

  notificationservice:
    restart: always
    environment:
      - VIRTUAL_HOST=notificationservice.localhost

  importservice:
    restart: always
    environment:
      - VIRTUAL_HOST=importservice.localhost
    volumes:
      - ./images:/data/files

  imageservice:
    restart: always
    environment:
      - VIRTUAL_HOST=imageservice.localhost
    volumes:
      - ./images:/data/files

  userservice:
    restart: always
    environment:
      - VIRTUAL_HOST=userservice.localhost

  pdfservice:
    restart: always
    environment:
      - VIRTUAL_HOST=pdfservice.localhost

  fileservice:
    restart: always
    environment:
      - VIRTUAL_HOST=fileservice.localhost
    volumes:
      - ./images:/data/files

  searchservice:
    restart: always
    environment:
      - VIRTUAL_HOST=searchservice.localhost

  solr:
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ../solrserver-config/solr-config:/opt/solr/server/solr
      - ../solrserver-config/solr-data:/solr-data

  xapi:
    restart: always
    environment:
      - VIRTUAL_HOST=xapiservice.localhost

  mongodb:
    restart: always
    volumes:
      - ./database:/data/db
      - ../solrserver-config/solr-data:/solr-data # needed by prepare script. Do not change it to solr as solr-data must have the correct rights before solr is started
