version: '2'
services:
  webserver:
    image: slidewiki/webproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-trier
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ../htpasswd:/etc/nginx/htpasswd # Not tracked as part of this repo

  platform:
    image: slidewiki/platform
    expose:
      - "80"
    environment:
      - PORT=80
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_DISCUSSION=http://discussionservice
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
      - SERVICE_URL_NOTIFICATION=http://notificationservice
      - SERVICE_URL_USER=http://userservice
      - SERVICE_URL_IMPORT=http://importservice
      - SERVICE_URL_FILE=http://fileservice
      - SERVICE_URL_SEARCH=http://searchservice
      - SERVICE_URL_IMAGE=http://imageservice
      - SERVICE_URL_PDF=http://pdfservice
      - SERVICE_VAR_IMPORT_HOST=importservice
    networks:
      - front-trier
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - imageservice

  deckservice:
    image: slidewiki/deckservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_FILE=http://fileservice
      - SERVICE_URL_IMAGE=http://imageservice
    depends_on:
      - fileservice
#      - imageservice
      - mongodb

  activitiesservice:
    image: slidewiki/activitiesservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - deckservice
      - userservice
      - mongodb

  discussionservice:
    image: slidewiki/discussionservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
      - SERVICE_URL_NOTIFICATION=http://notificationservice
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - activitiesservice
      - notificationservice
      - userservice
      - mongodb

  notificationservice:
    image: slidewiki/notificationservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - userservice
      - mongodb

  importservice:
    image: slidewiki/importservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_FILE=http://fileservice
    depends_on:
      - deckservice
      - fileservice
      - mongodb

  imageservice:
    image: slidewiki/imageservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_FILE=http://fileservice
    depends_on:
      - importservice
      - fileservice
      - mongodb

  userservice:
    image: slidewiki/userservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SMTP_PORT=25
      - SMTP_HOST=localhost
  #    - SMTP_FROM=me@hostername.org
  #    - SMTP_CLIENTNAME=
  #    - APIKey=
      - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
      - URL_PLATFORM=http://platform
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
    volumes:
      - /data/userservice/providerConfig_testing.json:/nodeApp/config.json
    depends_on:
  #    - platform
  #    - activitiesservice
      - mongodb

  pdfservice:
    image: slidewiki/pdfservice
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_PDF=http://pdfservice
      - SERVICE_URL_PLATFORM=http://platform
    depends_on:
      - deckservice

  fileservice:
    image: slidewiki/fileservice
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  searchservice:
    image: slidewiki/searchservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - userservice
      - solr
      - mongodb

  solr:
    image: solr
    container_name: solr
    expose:
      - "8983"
    networks:
      - back-trier
    depends_on:
      - mongodb

  #xapi:
  #  image: slidewiki/xapi-service
  #  expose:
  #    - "80"
  #  networks:
  #    - front-trier
  #  environment:
  #    - APPLICATION_PORT=80

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
        - "27017"
    networks:
      - back-trier
    command: mongod --replSet "rs0"

networks:
  front-trier: {}
  back-trier: {}
