version: '2'
services:
  webserver:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-trier
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ../htpasswd:/etc/nginx/htpasswd # Not tracked as part of this repo

  platform:
    image: slidewiki/platform
    expose:
      - "80"
    environment:
      - PORT=80
    networks:
      - front-trier

  deckservice:
    image: slidewiki/deckservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  activitiesservice:
    image: slidewiki/activitiesservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  discussionservice:
    image: slidewiki/discussionservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  notificationservice:
    image: slidewiki/notificationservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  importservice:
    image: slidewiki/importservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  imageservice:
    image: slidewiki/imageservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  userservice:
    image: slidewiki/userservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - VIRTUAL_HOST=userservice.localhost
      - SMTP_PORT=25
      - SMTP_HOST=localhost
  #    - SMTP_FROM=me@hostername.org
  #    - SMTP_CLIENTNAME=
  #    - APIKey=
      - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
      - URL_PLATFORM=http://platform.stable.slidewiki.org
      - URL_ACTIVITIESSERVICE=http://activitiesservice.stable.slidewiki.org
    volumes:
      - /data/slidewiki-deployment/docker-compose/providerConfig_stable.json:/nodeApp/config.json:ro

  pdfservice:
    image: slidewiki/pdfservice
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80

  fileservice:
    image: slidewiki/fileservice
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  searchservice:
    image: slidewiki/searchservice
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore

  solr:
    image: solr
    container_name: solr
    expose:
      - "8983"
    networks:
      - back-trier

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
        - "27017"
    networks:
      - back-trier
    command: mongod --replSet "rs0"

networks:
  front-trier: {}
  back-trier: {}
