version: '2'
services:
  webserver:
    restart: always
    environment:
      - BASENAME=experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.webserver"

  platform:
    restart: always
    environment:
      - VIRTUAL_HOST=experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.platform"

  deckservice:
    restart: always
    environment:
      - VIRTUAL_HOST=deckservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.deckservice"

  activitiesservice:
    restart: always
    environment:
      - VIRTUAL_HOST=activitiesservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.activitiesservice"

  discussionservice:
    restart: always
    environment:
      - VIRTUAL_HOST=discussionservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.discussionservice"

  notificationservice:
    restart: always
    environment:
      - VIRTUAL_HOST=notificationservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.notificationservice"

  importservice:
    restart: always
    environment:
      - VIRTUAL_HOST=importservice.experimental.slidewiki.org
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.importservice"

  imageservice:
    restart: always
    environment:
      - VIRTUAL_HOST=imageservice.experimental.slidewiki.org
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.imageservice"

  userservice:
    restart: always
    environment:
      - VIRTUAL_HOST=userservice.experimental.slidewiki.org
    volumes:
      - /data/slidewiki-deployment/docker-compose/providerConfig_experimental.json:/nodeApp/config.json:ro
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.userservice"

  pdfservice:
    restart: always
    environment:
      - VIRTUAL_HOST=pdfservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.pdfservice"

  fileservice:
    restart: always
    environment:
      - VIRTUAL_HOST=fileservice.experimental.slidewiki.org
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.fileservice"

  searchservice:
    restart: always
    environment:
      - VIRTUAL_HOST=searchservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.searchservice"

  solr:
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ../solrserver-config/solr-config:/opt/solr/server/solr:rw
      - solr-data:/solr-data
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.solr"

  xapi:
    restart: always
    environment:
      - VIRTUAL_HOST=xapiservice.experimental.slidewiki.org
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.xapi"

  mongodb:
    restart: always
    volumes:
      - mongo-data:/data/db
      - solr-data:/solr-data # needed by prepare script. Do not change it to solr as solr-data must have the correct rights before solr is started
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.mongodb"

  logger:
    image: slidewiki/logger
    restart: always
    volumes:
      - /data/maintenance/log:/fluentd/log
    networks:
      - front-trier
      - back-trier
    privileged: true

  maintenance:
    build: ../../maintenance/
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=maintenance.experimental.slidewiki.org
    networks:
      - front-trier
      - back-trier
    volumes:
      - /data/maintenance:/maintenance
      - files:/data/files # used to backup files
    depends_on:
      - mongodb
      - logger

volumes:
  mongo-data: {}
  solr-data: {}
  files: {}
