version: '2'
services:
  platform:
  #  build: /home/rmeissner/.git/slidewiki-platform/
    environment:
      - VIRTUAL_HOST=platform.localhost
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_DISCUSSION=http://discussionservice
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
      - SERVICE_URL_NOTIFICATION=http://notificationservice
      - SERVICE_URL_USER=http://userservice
      - SERVICE_URL_IMPORT=http://importservice
      - SERVICE_URL_FILE=http://fileservice
      - SERVICE_URL_SEARCH=http://searchservice
      - SERVICE_VAR_IMPORT_HOST=importservice
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - imageservice
      - userservice
      - pdfservice
      - fileservice

  deckservice:
    depends_on:
      - mongodb
      - fileservice
      - imageservice
    environment:
      - VIRTUAL_HOST=deckservice.localhost
      - SERVICE_URL_FILE=fileservice
      - SERVICE_URL_IMAGE=imageservice

  activitiesservice:
    depends_on:
      - mongodb
      - deckservice
      - userservice
    environment:
      - VIRTUAL_HOST=activitiesservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_USER=userservice

  discussionservice:
    depends_on:
      - mongodb
      - deckservice
      - userservice
      - notificationservice
      - activitiesservice
    environment:
      - VIRTUAL_HOST=discussionservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_USER=userservice
      - SERVICE_URL_NOTIFICATION=notificationservice
      - SERVICE_URL_ACTIVITIES=activitiesservice

  notificationservice:
    depends_on:
      - mongodb
      - userservice
    environment:
      - VIRTUAL_HOST=notificationservice.localhost
      - SERVICE_URL_USER=userservice

  importservice:
    depends_on:
      - mongodb
      - deckservice
      - fileservice
    environment:
      - VIRTUAL_HOST=importservice.localhost
      - SERVICE_URL_DECK=deckservice
      - SERVICE_URL_FILE=fileservice
    volumes:
      - ./images:/data/files/:rw

  imageservice:
    depends_on:
        - mongodb
    environment:
        - VIRTUAL_HOST=imageservice.localhost
    volumes:
      - ./images:/data/files/:rw

  userservice:
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=userservice.localhost

  pdfservice:
    environment:
      - VIRTUAL_HOST=pdfservice.localhost

  fileservice:
    environment:
      - VIRTUAL_HOST=fileservice.localhost
    volumes:
      - ./images:/data/files:ro

  searchservice:
    depends_on:
      - mongodb
      - solr
      - userservice
    environment:
      - VIRTUAL_HOST=searchservice.localhost
      - SERVICE_URL_USER=http://userservice

  solr:
    ports:
      - "8983:8983"
    volumes:
      - ./solrserver-config/solr-config:/opt/solr/server/solr:rw
      - ./solrserver-config/solr-data:/solr-data

  mongodb:
    volumes:
      - ./database:/data/db:rw
