version: '2'

networks:

  host:
    external: true

  internal:

volumes:

  mongo-data:
  solr-data:
  solr-data-nlp:
  files:

services:

  solr:
    image: slidewiki/solr:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "8983"
    networks:
      - internal
    volumes: 
      - solr-data:/solr-data
      - solr-data-nlp:/solr-data-nlp
    environment:
      - VIRTUAL_PORT=8983

  platform:
    image: slidewiki/platform:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "3000"
    networks:
      - host
      - internal
    depends_on:
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - tagservice
      - signalingservice
      - questionservice
    environment:
      - SERVICE_USER_APIKEY
      - SERVICE_USER_PRIVATE_RECAPTCHA_KEY=6LdNLyYTAAAAAFMC0J_zuVI1b9lXWZjPH6WLe-vJ
      - SERVICE_USER_PUBLIC_RECAPTCHA_KEY=6LdNLyYTAAAAAINDsVZRKG_E3l3Dvpp5sKboR1ET
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_DISCUSSION=http://discussionservice
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
      - SERVICE_URL_NOTIFICATION=http://notificationservice
      - SERVICE_URL_TAG=http://tagservice
      - SERVICE_URL_QUESTION=http://questionservice
      - SERVICE_URL_USER
      - SERVICE_URL_IMPORT
      - SERVICE_URL_FILE
      - SERVICE_URL_SEARCH
      - SERVICE_URL_PDF
      - SERVICE_VAR_IMPORT_HOST
      - SERVICE_PROTOCOL_IMPORT
      - SERVICE_PORT_IMPORT
      - SERVICE_URL_SIGNALING
      - SMTP_PORT=
      - SMTP_HOST=
      - SMTP_FROM=
      - SMTP_TO=
      - SMTP_ENABLED=
      - LOGGING_LEVEL

  deckservice:
    image: slidewiki/deckservice:${SLIDEWIKI_VERSION}
    restart: always
    ports:
      - "4000:3000"
    networks:
      - internal
    depends_on:
      - userservice
    environment:
      - SECRET_REVIEW_KEY
      - SERVICE_URL_FILE
      - SERVICE_URL_USER
      - JWT_SERIAL

  unoconvservice:
    image: zrrrzzt/docker-unoconv-webservice
    restart: always
    expose:
      - "3000"
    networks:
      - internal
    environment:
      - PAYLOAD_MAX_SIZE=314572800

  signalingservice:
    image: slidewiki/webrtcsignalingservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "4900"
    networks:
      - host
    volumes:
      - ./signalingservice/twitterConfig.json:/nodeApp/config.json:ro
    environment:
      - APPLICATION_PORT=4900

  activitiesservice:
    image: slidewiki/activitiesservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "4300"
    networks:
      - host
      - internal
    depends_on:
      - deckservice
      - userservice
      - notificationservice
    environment:
      - APPLICATION_PORT=4300

  discussionservice:
    image: slidewiki/discussionservice:${SLIDEWIKI_VERSION}
    expose:
      - "80"
    networks:
      - internal
    depends_on:
      - deckservice
      - userservice
    environment:
      - APPLICATION_PORT=80

  notificationservice:
    image: slidewiki/notificationservice:${SLIDEWIKI_VERSION}
    networks:
      - internal
    environment:
      - APPLICATION_PORT=80
    depends_on:
      - userservice

  importservice:
    image: slidewiki/importservice:${SLIDEWIKI_VERSION}
    expose:
      - "4500"
    networks:
      - host
      - internal
    depends_on:
      - deckservice
      - fileservice
      - unoconvservice
    environment:
      - APPLICATION_PORT=4500
      - SERVICE_HOST_UNOCONV=unoconvservice
      - SERVICE_URL_FILE
      - JWT_SERIAL

  userservice:
    image: slidewiki/userservice:${SLIDEWIKI_VERSION}
    expose:
      - "4100"
    networks:
      - host
      - internal
    volumes:
      - ./userservice/providerConfig.json:/nodeApp/config.json
    environment:
      - APPLICATION_PORT=4100
      - URL_PLATFORM=http://${BASE_DOMAIN}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - APIKEY=${SERVICE_USER_APIKEY}
      - SECRET_REVIEW_KEY
      - JWT_SERIAL
      - SMTP_PORT
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_CLIENTNAME=
      - SMTP_ENABLED

  pdfservice:
    image: slidewiki/pdfservice:${SLIDEWIKI_VERSION}
    expose:
      - "4700"
    networks:
      - host
      - internal
    depends_on:
      - deckservice
      - userservice
    environment:
      - APPLICATION_PORT=4700
      - SERVICE_URL_PLATFORM=http://${BASE_DOMAIN}
      - SERVICE_URL_PDF

  fileservice:
    image: slidewiki/fileservice:${SLIDEWIKI_VERSION}
    expose:
      - "4600"
    networks:
      - host
      - internal
    volumes:
      - files:/data/files
    depends_on:
      - deckservice
    environment:
      - APPLICATION_PORT=4600
      - APPLICATION_PATH=/data/files

  searchservice:
    image: slidewiki/searchservice:${SLIDEWIKI_VERSION}
    expose:
      - "80"
    networks:
      - internal
    depends_on:
      - deckservice
      - userservice
      - solr
    environment:
      - APPLICATION_PORT=80
      - SOLR_CORE=swikcore
      - SOLR_HOST=solr

  searchindexer:
    image: slidewiki/searchservice:latest-dev
    command: 'node worker'
    networks:
      - internal
    depends_on:
      - solr
    environment:
      - SERVICE_URL_DECK
      - SERVICE_URL_USER
      - SOLR_CORE=swikcore
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=2
      - JOB_TYPES=searchUpdate

  tagservice:
    image: slidewiki/tagservice:${SLIDEWIKI_VERSION}
    expose:
      - "80"
    networks:
      - internal
    environment:
      - APPLICATION_PORT=80

  nlpstore:
    image: slidewiki/nlpstore:${SLIDEWIKI_VERSION}
    expose:
      - "80"
    networks:
      - host
      - internal
    environment:
      - APPLICATION_PORT=80
      - SERVICE_URL_DECK
      - SERVICE_URL_NLP=http://nlpservice:9000
    depends_on:
      - deckservice

  nlpservice:
    image: slidewiki/nlpservice:${SLIDEWIKI_VERSION}
    expose:
      - "9000"
    networks:
      - internal
    environment:
      - APPLICATION_SECRET=sndv9sd98adpvnaa0wefe0fa04nvpdnvp9e+-.sfw03fs
    depends_on:
      - deckservice
      - nlpstore

  questionservice:
    image: slidewiki/questionservice:${SLIDEWIKI_VERSION}
    expose:
      - "80"
    networks:
      - internal
    environment:
      - APPLICATION_PORT=80
    depends_on:
      - deckservice
