version: '2'

volumes:

  solr-data:
  solr-data-nlp:
  learninglocker-data:
  files:
    external: true

services:

  solr:
    image: slidewiki/solr:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "8983"
    volumes: 
      - solr-data:/solr-data
      - solr-data-nlp:/solr-data-nlp

  platform:
    image: slidewiki/platform:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - 3000
    depends_on:
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - pdfservice
      - fileservice
      - searchservice
      - tagservice
      - signalingservice
      - questionservice
      - nlpservice
    environment:
      - SERVICE_USER_PRIVATE_RECAPTCHA_KEY=6LdNLyYTAAAAAFMC0J_zuVI1b9lXWZjPH6WLe-vJ
      - SERVICE_USER_PUBLIC_RECAPTCHA_KEY=6LdNLyYTAAAAAINDsVZRKG_E3l3Dvpp5sKboR1ET
      - SERVICE_USER_APIKEY
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_DISCUSSION=${BASE_SERVICE_URL}:{SERVICE_PORT_DISCUSSION}
      - SERVICE_URL_ACTIVITIES=${BASE_SERVICE_URL}:{SERVICE_PORT_ACTIVITIES}
      - SERVICE_URL_NOTIFICATION=${BASE_SERVICE_URL}:{SERVICE_PORT_NOTIFICATION}
      - SERVICE_URL_TAG=${BASE_SERVICE_URL}:{SERVICE_PORT_TAG}
      - SERVICE_URL_QUESTION=${BASE_SERVICE_URL}:{SERVICE_PORT_QUESTION}
      - SERVICE_URL_USER
      - SERVICE_URL_FILE
      - SERVICE_URL_SEARCH
      - SERVICE_URL_PDF
      - SERVICE_URL_SIGNALING
      - SERVICE_URL_IMPORT
      - SERVICE_VAR_IMPORT_HOST
      - SERVICE_PROTOCOL_IMPORT
      - SERVICE_PORT_IMPORT
      - SMTP_PORT
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_TO
      - SMTP_ENABLED
      - LOGGING_LEVEL

  deckservice:
    image: slidewiki/deckservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_DECK}"
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_DECK}
      - SECRET_REVIEW_KEY
      - SERVICE_URL_FILE
      - SERVICE_URL_USER
      - JWT_SERIAL

  unoconvservice:
    image: zrrrzzt/docker-unoconv-webservice
    network_mode: host
    expose:
      - "${SERVICE_PORT_UNOCONV}"
    environment:
      - SERVER_PORT=${SERVICE_PORT_UNOCONV}
      - PAYLOAD_MAX_SIZE=314572800

  signalingservice:
    image: slidewiki/webrtcsignalingservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_SIGNALING}"
    volumes:
      - ./signalingservice/twitterConfig.json:/nodeApp/config.json:ro
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_SIGNALING}

  activitiesservice:
    image: slidewiki/activitiesservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_ACTIVITIES}"
    depends_on:
      - deckservice
      - notificationservice
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_ACTIVITIES}
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_NOTIFICATION=${BASE_SERVICE_URL}:{SERVICE_PORT_NOTIFICATION}
      - SERVICE_URL_USER
      - LRS_ENDPOINT
      - LRS_PUBLIC_KEY
      - LRS_SECRET

  discussionservice:
    image: slidewiki/discussionservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_DISCUSSION}"
    depends_on:
      - deckservice
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_DISCUSSION}
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_USER

  notificationservice:
    image: slidewiki/notificationservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_NOTIFICATION}"
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_NOTIFICATION}
      - SERVICE_URL_USER

  importservice:
    image: slidewiki/importservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_IMPORT}"
    depends_on:
      # - deckservice
      - fileservice
      - unoconvservice
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_IMPORT}
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_UNOCONV=${BASE_SERVICE_URL}:${SERVICE_PORT_UNOCONV}
      - SERVICE_URL_FILE
      - JWT_SERIAL

  userservice:
    image: slidewiki/userservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "4100"
    volumes:
      - ./userservice/providerConfig.json:/nodeApp/config.json
    environment:
      - APPLICATION_PORT=4100
      - URL_PLATFORM=http://${BASE_DOMAIN}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - APIKEY=${SERVICE_USER_APIKEY}
      - SECRET_REVIEW_KEY
      - JWT_SERIAL
      - SMTP_PORT
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_CLIENTNAME=
      - SMTP_ENABLED

  pdfservice:
    image: slidewiki/pdfservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "4700"
    depends_on:
      - deckservice
    environment:
      - APPLICATION_PORT=4700
      - SERVICE_URL_PLATFORM=http://${BASE_DOMAIN}
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_PDF
      - SERVICE_URL_USER

  fileservice:
    image: slidewiki/fileservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_FILE}"
    volumes:
      - files:/data/files
    depends_on:
      - deckservice
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_FILE}
      - APPLICATION_PATH=/data/files
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_PLATFORM=http://${BASE_DOMAIN}

  searchservice:
    image: slidewiki/searchservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "5000"
    depends_on:
      - deckservice
      - solr
      - searchindexer
    environment:
      - APPLICATION_PORT=5000
      - SOLR_CORE=swikcore
      - SOLR_HOST
      - SOLR_CONFIG_PORT
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_USER

  searchindexer:
    image: slidewiki/searchservice:latest-dev
    command: 'node worker'
    network_mode: host
    depends_on:
      - deckservice
      - solr
    environment:
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_USER
      - SOLR_CORE=swikcore
      - SOLR_HOST
      - SOLR_CONFIG_PORT
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=2
      - JOB_TYPES=searchUpdate

  tagservice:
    image: slidewiki/tagservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_TAG}"
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_TAG}

  nlpstore:
    image: slidewiki/nlpstore:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_NLPSTORE}"
    depends_on:
      - deckservice
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_NLPSTORE}
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_NLP=${BASE_SERVICE_URL}:9000

  nlpservice:
    image: slidewiki/nlpservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "9000"
    depends_on:
      - deckservice
      - nlpstore
    environment:
      - APPLICATION_SECRET=sndv9sd98adpvnaa0wefe0fa04nvpdnvp9e+-.sfw03fs
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}
      - SERVICE_URL_NLPSTORE=${BASE_SERVICE_URL}:${SERVICE_PORT_NLPSTORE}

  questionservice:
    image: slidewiki/questionservice:${SLIDEWIKI_VERSION}
    network_mode: host
    expose:
      - "${SERVICE_PORT_QUESTION}"
    depends_on:
      - deckservice
    environment:
      - APPLICATION_PORT=${SERVICE_PORT_QUESTION}
      - SERVICE_URL_DECK=${BASE_SERVICE_URL}:${SERVICE_PORT_DECK}


  redis:
    network_mode: host
    image: redis:4-alpine

  xapi:
    image: learninglocker/xapi-service:${LEARNINGLOCKER_XAPI_VERSION}
    network_mode: host
    expose:
      - ${SERVICE_PORT_XAPI}
    environment:
      - EXPRESS_PORT=${SERVICE_PORT_XAPI}
    depends_on:
      - redis

  learninglockerapi:
    image: slidewiki/learninglocker2-docker
    command: "node api/dist/server"
    network_mode: host
    expose:
      - ${SERVICE_PORT_LEARNINGLOCKER_API}
    volumes:
      - learninglocker-data:/opt/learninglocker/storage
    environment:
      - DOMAIN_NAME=${BASE_DOMAIN}
      - APP_SECRET=${LEARNINGLOCKER_SECRET}
      - UI_PORT=${SERVICE_PORT_LEARNINGLOCKER}
      - API_PORT=${SERVICE_PORT_LEARNINGLOCKER_API}
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURED
      - SMTP_USER
      - SMTP_PASS
      - MONGO_URL=${LEARNINGLOCKER_MONGO_URL}
    depends_on:
      - redis

  learninglockerui:
    image: slidewiki/learninglocker2-docker
    command: "./entrypoint-ui.sh"
    network_mode: host
    expose:
      - ${SERVICE_PORT_LEARNINGLOCKER}
    volumes:
      - learninglocker-data:/opt/learninglocker/storage
    environment:
      - DOMAIN_NAME=${BASE_DOMAIN}
      - APP_SECRET=${LEARNINGLOCKER_SECRET}
      - UI_PORT=${SERVICE_PORT_LEARNINGLOCKER}
      - API_PORT=${SERVICE_PORT_LEARNINGLOCKER_API}
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURED
      - SMTP_USER
      - SMTP_PASS
      - MONGO_URL=${LEARNINGLOCKER_MONGO_URL}
    depends_on:
      - redis
      - learninglockerapi
      - learninglockerworker

  learninglockerworker:
    image: slidewiki/learninglocker2-docker
    command: "node worker/dist/server"
    network_mode: host
    expose: []
    volumes:
      - learninglocker-data:/opt/learninglocker/storage
    environment:
      - DOMAIN_NAME=${BASE_DOMAIN}
      - APP_SECRET=${LEARNINGLOCKER_SECRET}
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURED
      - SMTP_USER
      - SMTP_PASS
      - REDIS_HOST
      - MONGO_URL=${LEARNINGLOCKER_MONGO_URL}
    depends_on:
      - redis
