version: '2'

networks:

  front-trier: {}
  back-trier: {}

services:

  mongodb:
    image: mongo:3.4
    restart: always
    expose:
      - "27017"
    networks:
      - back-trier
    command: mongod --replSet "rs0"

  solr:
    image: slidewiki/solr:${SLIDEWIKI_VERSION}
    restart: always
    environment:
      - VIRTUAL_PORT=8983
    expose:
      - "8983"
    networks:
      - front-trier
      - back-trier
    depends_on:
      - mongodb

  webserver:
    image: slidewiki/webproxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-trier
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd

  platform:
    image: slidewiki/platform:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - PORT=80
    networks:
      - front-trier
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - tagservice

  deckservice:
    image: slidewiki/deckservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SECRET_REVIEW_KEY=${SECRET_REVIEW_KEY}
      - SERVICE_URL_USER=http://userservice
      - SERVICE_URL_FILE=http://fileservice
      - SERVICE_URL_TAG=http://tagservice
      # - SERVICE_URL_TRANSLATION=http://translationservice
    depends_on:
      - userservice
      - fileservice
      - tagservice
      # - translationservice
      - mongodb

  unoconvservice:
    image: zrrrzzt/docker-unoconv-webservice
    restart: always
    environment:
      - VIRTUAL_PORT=3000
      - PAYLOAD_MAX_SIZE=314572800
    expose:
      - "3000"
    networks:
      - front-trier
      - back-trier

  activitiesservice:
    image: slidewiki/activitiesservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_NOTIFICATION=http://notificationservice
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - deckservice
      - notificationservice
      - userservice
      - mongodb

  discussionservice:
    image: slidewiki/discussionservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - deckservice
      - userservice
      - mongodb

  notificationservice:
    image: slidewiki/notificationservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - userservice
      - mongodb

  importservice:
    image: slidewiki/importservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_FILE=http://fileservice
      - SERVICE_HOST_UNOCONV=unoconvservice
    depends_on:
      - deckservice
      - fileservice
      - unoconvservice
      - mongodb

  userservice:
    image: slidewiki/userservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SECRET_REVIEW_KEY=${SECRET_REVIEW_KEY}
      - SERVICE_URL_ACTIVITIES=http://activitiesservice
    depends_on:
      - activitiesservice
      - mongodb

  pdfservice:
    image: slidewiki/pdfservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - SERVICE_URL_DECK=http://deckservice
    depends_on:
      - deckservice

  fileservice:
    image: slidewiki/fileservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  searchservice:
    image: slidewiki/searchservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SOLR_HOST=solr
      - SERVICE_URL_DECK=http://deckservice
      - SERVICE_URL_USER=http://userservice
    depends_on:
      - userservice
      - solr
      - mongodb

  #xapi:
  #  image: slidewiki/xapi-service:${SLIDEWIKI_VERSION}
  #  restart: always
  #  expose:
  #    - "80"
  #  networks:
  #    - front-trier
  #  environment:
  #    - APPLICATION_PORT=80

  tagservice:
    image: slidewiki/tagservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  # nlpstore:
  #   image: slidewiki/nlpstore:${SLIDEWIKI_VERSION}
  #   restart: always
  #   expose:
  #     - "80"
  #   networks:
  #     - front-trier
  #     - back-trier
  #   environment:
  #     - APPLICATION_PORT=80
  #     - DATABASE_PORT=27017
  #     - DATABASE_URL=mongodb
  #     - SERVICE_URL_DECK=http://deckservice
  #     - SERVICE_URL_NLP=http://nlpservice
  #   depends_on:
  #     - deckservice
  #     - nlpservice
  #     - mongodb
