version: '2'

volumes:

  mongo-data: {}
  solr-data: {}
  learninglocker-data: {}
  files: {}
  certs: {}

services:

  ##
  ##  Infrastructure services
  ##

  maintenance:
    build: ../maintenance/
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=maintenance.${BASE_DOMAIN}
    networks:
      - front-trier
      - back-trier
    volumes:
      - ${MAINTENANCE_DIR}:/maintenance
      - files:/data/files # used to backup files
    depends_on:
      - mongodb
      - logger

  logger:
    image: slidewiki/logger:latest
    restart: always
    volumes:
      - ${MAINTENANCE_DIR}/log:/fluentd/log
    ports:
      - "24224:24224"
    networks:
      - front-trier
      - back-trier
    privileged: true

  mongodb:
    volumes:
      - mongo-data:/data/db
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.mongodb"

  redis:
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.redis"

  webserver:
    environment:
      - BASENAME=${BASE_DOMAIN}
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.webserver"

  ##
  ##  SlideWiki Platform
  ##

  platform:
    environment:
      - VIRTUAL_HOST=${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=http://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=http://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=http://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=http://importservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=http://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=http://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=http://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_TAG=http://tagservice.${BASE_DOMAIN}
      - SERVICE_URL_QUESTION=http://questionservice.${BASE_DOMAIN}
      - SERVICE_VAR_IMPORT_HOST=importservice.${BASE_DOMAIN}
      - SERVICE_PROTOCOL_IMPORT=http
      - SERVICE_PORT_IMPORT=80
      - SERVICE_USER_APIKEY=${APIKEY}
      - SERVICE_USER_PRIVATE_RECAPTCHA_KEY=${RECAPTCHA_PRIVATE_KEY}
      - SERVICE_USER_PUBLIC_RECAPTCHA_KEY=${RECAPTCHA_PUBLIC_KEY}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - SMTP_CLIENTNAME=${SMTP_CLIENTNAME}
      - SSO_ENABLED=${SSO_ENABLED}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.platform"

  ##
  ##  SlideWiki Basic Services
  ##

  deckservice:
    environment:
      - VIRTUAL_HOST=deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=http://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_TAG=http://tagservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
      - SERVICE_URL_TRANSLATION=http://translationservice.${BASE_DOMAIN}
      - JWT_SERIAL=${JWT_SERIAL}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.deckservice"

  userservice:
    environment:
      - VIRTUAL_HOST=userservice.${BASE_DOMAIN}
      - URL_PLATFORM=http://${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=http://activitiesservice.${BASE_DOMAIN}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_CLIENTNAME=${SMTP_CLIENTNAME}
      - SMTP_ENABLED=${SMTP_ENABLED}
      - JWT_SERIAL=${JWT_SERIAL}
      - APIKEY=${APIKEY}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=http://fileservice.${BASE_DOMAIN}
      - LTI_env_user_service
      - LTI_ID=${LTI_ID}
      - LTI_KEY=${LTI_KEY}
      - LTI_SECRET=${LTI_SECRET}
    volumes:
      - ./userservice/providerConfig.json:/nodeApp/config.json
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.userservice"

  fileservice:
    environment:
      - VIRTUAL_HOST=fileservice.${BASE_DOMAIN}
      - JWT_SERIAL=${JWT_SERIAL}
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.fileservice"

  activitiesservice:
    environment:
      - VIRTUAL_HOST=activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=http://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
      - URL_PLATFORM=http://${BASE_DOMAIN}
      - LRS_ENDPOINT=http://xapi/data/xAPI
      - LRS_PUBLIC_KEY=${XAPI_CLIENT_KEY}
      - LRS_SECRET=${XAPI_CLIENT_SECRET}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.activitiesservice"

  notificationservice:
    environment:
      - VIRTUAL_HOST=notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.notificationservice"

  discussionservice:
    environment:
      - VIRTUAL_HOST=discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.discussionservice"

  tagservice:
    environment:
      - VIRTUAL_HOST=tagservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=http://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=http://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=http://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=http://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_IMAGE=http://imageservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=http://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=http://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=http://importservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.tagservice"

  questionservice:
    environment:
      - VIRTUAL_HOST=questionservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.questionservice"

  ##
  ## SlideWiki Search Services
  ##

  searchservice:
    environment:
      - VIRTUAL_HOST=searchservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.searchservice"

  searchindexer:
    environment:
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.searchindexer"

  solr:
    volumes:
      - solr-data:/solr-data
    environment:
      - VIRTUAL_HOST=solr.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.solr"

  ##
  ##  SlideWiki Import/Export Services
  ##

  importservice:
    environment:
      - VIRTUAL_HOST=importservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=http://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_UNOCONV=http://unoconvservice.${BASE_DOMAIN}
      - JWT_SERIAL=${JWT_SERIAL}
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.importservice"

  pdfservice:
    environment:
      - VIRTUAL_HOST=pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=http://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_PLATFORM=http://${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.pdfservice"

  unoconvservice:
    restart: always
    environment:
      - VIRTUAL_HOST=unoconvservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.unoconv"

  ##
  ##  SlideWiki Presentation Room Service
  ##

  signalingservice:
    environment:
      - VIRTUAL_HOST=signalingservice.${BASE_DOMAIN}
    volumes:
      - ./signalingservice/twitterConfig.json:/nodeApp/config.json:ro
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.signalingservice"

  ##
  ## SlideWiki NLP Services
  ##

  nlpstore:
    environment:
      - VIRTUAL_HOST=nlpstore.${BASE_DOMAIN}
      - SERVICE_URL_DECK=http://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=http://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=http://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=http://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=http://userservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=http://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_IMAGE=http://imageservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=http://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=http://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=http://importservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.nlpstore"

#  nlpservice:
#    environment:
#      - APPLICATION_SECRET=${NLP_APPLICATION_SECRET}
#      - SERVICE_URL_DECK=deckservice.${BASE_DOMAIN}
#      - SERVICE_URL_NLPSTORE=nlpstore.${BASE_DOMAIN}
#      - VIRTUAL_HOST=nlpservice.${BASE_DOMAIN}
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "localhost:24224"
#        tag: "slidewiki.nlpservice"

  ##
  ##  SlideWiki Learning Analytics Services
  ##

  xapi:
    environment:
      - VIRTUAL_HOST=xapi.${DOMAIN_NAME}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.xapi"

  learninglocker:
    environment:
      - VIRTUAL_HOST=learninglocker.${BASE_DOMAIN}
      - VIRTUAL_PORT=3000
    depends_on:
      - logger
    volumes:
      - learninglocker-data:/opt/learninglocker/storage
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.learninglockerui"

  learninglockerapi:
    environment:
      - VIRTUAL_HOST=api.learninglocker.${BASE_DOMAIN}
      - VIRTUAL_PORT=8080
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - SMTP_SECURED
      - SMTP_IGNORE_TLS
    volumes:
      - learninglocker-data:/opt/learninglocker/storage
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.learninglockerapi"

  learninglockerworker:
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - SMTP_SECURED
      - SMTP_IGNORE_TLS
    depends_on:
      - logger
    volumes:
      - learninglocker-data:/opt/learninglocker/storage
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.learninglockerworker"
