version: '2'

networks:

  front-trier: {}
  back-trier: {}

services:

  ##
  ##  Infrastructure services
  ##

  mongodb:
    image: mongo:3.4
    restart: always
    expose:
      - "27017"
    networks:
      - back-trier
    command: mongod --replSet "rs0"

  redis:
      image: redis:4-alpine
      restart: unless-stopped

  webserver:
    image: slidewiki/webproxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-trier
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd

  ##
  ##  SlideWiki Platform
  ##

  platform:
    image: slidewiki/platform:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - PORT=80
    networks:
      - front-trier
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - tagservice
      - signalingservice
      - questionservice

  ##
  ##  SlideWiki Basic Services
  ##

  deckservice:
    image: slidewiki/deckservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SECRET_REVIEW_KEY=${SECRET_REVIEW_KEY}
    depends_on:
      - fileservice
      - mongodb
      - userservice

  userservice:
    image: slidewiki/userservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SECRET_REVIEW_KEY=${SECRET_REVIEW_KEY}
    depends_on:
      - mongodb

  fileservice:
    image: slidewiki/fileservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  activitiesservice:
    image: slidewiki/activitiesservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - deckservice
      - notificationservice
      - userservice
      - xapi
      - mongodb

  notificationservice:
    image: slidewiki/notificationservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - userservice
      - mongodb

  discussionservice:
    image: slidewiki/discussionservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - deckservice
      - userservice
      - mongodb

  tagservice:
    image: slidewiki/tagservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  questionservice:
    image: slidewiki/questionservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - deckservice
      - mongodb

  ##
  ## SlideWiki Search Services
  ##

  searchservice:
    image: slidewiki/searchservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SOLR_HOST=solr
    depends_on:
      - userservice
      - solr
      - searchindexer
      - mongodb

  searchindexer:
    image: slidewiki/searchservice:${SLIDEWIKI_VERSION}
    restart: always
    command: 'node worker'
    networks:
      - back-trier
    environment:
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SOLR_HOST=solr
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=2
      - JOB_TYPES=searchUpdate
    depends_on:
      - deckservice
      - solr
      - mongodb

  solr:
    image: slidewiki/solr:${SLIDEWIKI_VERSION}
    restart: always
    environment:
      - VIRTUAL_PORT=8983
    expose:
      - "8983"
    networks:
      - front-trier
      - back-trier
    depends_on:
      - mongodb

  ##
  ##  SlideWiki Import/Export Services
  ##

  importservice:
    image: slidewiki/importservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - unoconvservice
      - deckservice
      - fileservice
      - mongodb

  pdfservice:
    image: slidewiki/pdfservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
    depends_on:
      - deckservice

  unoconvservice:
    image: zrrrzzt/docker-unoconv-webservice
    restart: always
    environment:
      - VIRTUAL_PORT=3000
      - PAYLOAD_MAX_SIZE=314572800
    expose:
      - "3000"
    networks:
      - front-trier
      - back-trier

  ##
  ##  SlideWiki Presentation Room Service
  ##

  signalingservice:
    image: slidewiki/webrtcsignalingservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb

  ##
  ## SlideWiki NLP Services
  ##

  nlpstore:
    image: slidewiki/nlpstore:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

#  nlpservice:
#    image: slidewiki/nlpservice:${SLIDEWIKI_VERSION}
#    restart: on-failure:5
#    networks:
#      - front-trier
#      - back-trier
#    expose:
#      - "9000"

  ##
  ##  SlideWiki Learning Analytics Services
  ##

  xapi:
    image: learninglocker/xapi-service:2.2.7
    restart: unless-stopped
    expose:
      - 80
    environment:
      - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
      - REDIS_URL=redis://redis:6379/0
      - EXPRESS_PORT=80
    networks:
      - front-trier
      - back-trier
    depends_on:
      - mongodb
      - redis

  learninglocker:
    image: slidewiki/learninglocker2-docker:latest
    command: "./entrypoint-ui.sh"
    expose:
      - 3000
    environment:
      - DOMAIN_NAME=learninglocker.${BASE_DOMAIN}
      - APP_SECRET=${LEARNINGLOCKER_SECRET}
      - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
      - UI_PORT=3000
      - API_PORT=8080
      - API_HOST=learninglockerapi
    restart: unless-stopped
    depends_on:
      - redis
      - learninglockerapi
      - mongodb

  learninglockerapi:
    image: slidewiki/learninglocker2-docker:latest
    command: "node api/dist/server"
    expose:
      - 8080
    environment:
      - DOMAIN_NAME=learninglocker.${BASE_DOMAIN}
      - APP_SECRET=${LEARNINGLOCKER_SECRET}
      - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
      - API_PORT=8080
    restart: unless-stopped
    networks:
      - front-trier
      - back-trier
    depends_on:
      - redis
      - learninglockerworker
      - mongodb

  learninglockerworker:
    image: slidewiki/learninglocker2-docker:latest
    command: "node worker/dist/server"
    expose: []
    environment:
      - DOMAIN_NAME=learninglocker.${BASE_DOMAIN}
      - APP_SECRET=${LEARNINGLOCKER_SECRET}
      - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
