version: '2'

volumes:

  mongo-data: {}
  solr-data: {}
  files: {}
  certs: {}
  prometheus-data: {}
  grafana-data: {}

networks:

  front-trier: {}
  back-trier: {}
  metrics-net:
    driver: bridge

services:

# ______________________________ CENTRAL PROXY ________________________________
  webserver:
    environment:
      - BASENAME=${BASE_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.webserver"

# ____________________________ LETSENCRYPT SUPPORT ____________________________
# uncomment if you want to automatically acquire TLS certs
#letsencrypt:
#  image: jrcs/letsencrypt-nginx-proxy-companion
#  restart: always
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock:ro
#    - certs:/etc/nginx/certs:rw
#  volumes_from:
#    - webserver

# _____________________________ MAINTENANCE HATCH _____________________________
# serves backups and log files via HTTP
  maintenance:
    build: ../maintenance/
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=maintenance.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=maintenance.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    networks:
      - front-trier
      - back-trier
    volumes:
      - ${MAINTENANCE_DIR}:/maintenance
      - files:/data/files # used to backup files
    depends_on:
      - mongodb
      - logger

# __________________________________ LOGGER ___________________________________
  logger:
    image: slidewiki/logger:latest
    restart: always
    volumes:
      - ${MAINTENANCE_DIR}/log:/fluentd/log
    ports:
      - "24224:24224"
    networks:
      - front-trier
      - back-trier
    privileged: true

# __________________________________ METRICS __________________________________

  # metrics database
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      #- '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    networks:
      - metrics-net

  # fancy visualization
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=dev
      - GF_SECURITY_ADMIN_PASSWORD=killywilly
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=metrics.${BASE_DOMAIN}
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - front-trier
      - metrics-net

  # container metrics
  cadvisor:
    image: google/cadvisor:v0.26.1
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - metrics-net

  # host metrics
  nodeexporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sys'
      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    ports:
      - 9100:9100
    networks:
      - metrics-net

# _________________________________ DATABASE __________________________________

  mongodb:
    volumes:
      - mongo-data:/data/db
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.mongodb"

  solr:
    volumes:
      - solr-data:/solr-data
    environment:
      - VIRTUAL_HOST=solr.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=solr.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.solr"

# _________________________________ SLIDEWIKI _________________________________
  platform:
    environment:
      - VIRTUAL_HOST=${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=https://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=https://importservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=https://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_TAG=https://tagservice.${BASE_DOMAIN}
      - SERVICE_VAR_IMPORT_HOST=importservice.${BASE_DOMAIN}
      - SERVICE_PROTOCOL_IMPORT=https
      - SERVICE_PORT_IMPORT=443
      - LETSENCRYPT_HOST=${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - SERVICE_USER_APIKEY=${API_KEY}
      - SERVICE_USER_PRIVATE_RECAPTCHA_KEY=${RECAPTCHA_PRIVATE_KEY}
      - SERVICE_USER_PUBLIC_RECAPTCHA_KEY=${RECAPTCHA_PUBLIC_KEY}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.platform"

  deckservice:
    environment:
      - VIRTUAL_HOST=deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=deckservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.deckservice"

  unoconvservice:
    restart: always
    environment:
      - VIRTUAL_HOST=unoconvservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=unoconvservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.unoconv"

  activitiesservice:
    environment:
      - VIRTUAL_HOST=activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=activitiesservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.activitiesservice"

  discussionservice:
    environment:
      - VIRTUAL_HOST=discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=discussionservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.discussionservice"

  notificationservice:
    environment:
      - VIRTUAL_HOST=notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=notificationservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.notificationservice"

  importservice:
    environment:
      - VIRTUAL_HOST=importservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_HOST_UNOCONV=unoconvservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=importservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.importservice"

  userservice:
    environment:
      - VIRTUAL_HOST=userservice.${BASE_DOMAIN}
      - URL_PLATFORM=https://${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SMTP_PORT
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_CLIENTNAME
      - JWT_SERIAL
      - APIKey=${API_KEY}
      - LETSENCRYPT_HOST=userservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    volumes:
      - ./userservice/providerConfig.json:/nodeApp/config.json
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.userservice"

  pdfservice:
    environment:
      - VIRTUAL_HOST=pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_PLATFORM=https://${BASE_DOMAIN}
      - LETSENCRYPT_HOST=pdfservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.pdfservice"

  fileservice:
    environment:
      - VIRTUAL_HOST=fileservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=fileservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.fileservice"

  searchservice:
    environment:
      - VIRTUAL_HOST=searchservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=searchservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.searchservice"

  #xapi:
  #  environment:
  #    - VIRTUAL_HOST=xapiservice.${BASE_DOMAIN}
  #    - LETSENCRYPT_HOST=xapiservice.${BASE_DOMAIN}
  #    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  #    - LETSENCRYPT_TEST=true
  #  depends_on:
  #    - logger
  #  logging:
  #    driver: fluentd
  #    options:
  #      fluentd-address: "localhost:24224"
  #      tag: "slidewiki.xapi"

  tagservice:
    environment:
      - VIRTUAL_HOST=tagservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=https://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=https://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_IMAGE=https://imageservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=https://importservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=tagservice.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.tagservice"

  nlpstore:
    environment:
      - VIRTUAL_HOST=nlpstore.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=https://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=https://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_IMAGE=https://imageservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=https://importservice.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=nlpstore.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "slidewiki.nlpstore"
