webserver:
  image: jwilder/nginx-proxy
  restart: on-failure:5
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro

platform:
  image: slidewiki/platform
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - PORT=80
    - VIRTUAL_HOST=platform.localhost
    - SERVICE_URL_DECK="http://deckservice.localhost"
    - SERVICE_URL_DISCUSSION="http://discussionservice.localhost"
    - SERVICE_URL_ACTIVITIES="http://activitiesservice.localhost"
    - SERVICE_URL_NOTIFICATION="http://notificationservice.localhost"
    - SERVICE_URL_USER="http://userservice.localhost"
    - SERVICE_URL_IMPORT="http://importservice.localhost"
    - SERVICE_URL_FILE="http://fileservice.localhost"
    - SERVICE_VAR_IMPORT_HOST="importservice.localhost"
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.platform"


deckservice:
  image: slidewiki/deckservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.localhost
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.deckservice"


activitiesservice:
  image: slidewiki/activitiesservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=activitiesservice.localhost
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.activitiesservice"

discussionservice:
  image: slidewiki/discussionservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=discussionservice.localhost
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.discussionservice"

notificationservice:
  image: slidewiki/notificationservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=notificationservice.localhost
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.notificationservice"

importservice:
  image: slidewiki/importservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=importservice.localhost
  volumes_from:
    - volume_share
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.importservice"

userservice:
  image: slidewiki/userservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=userservice.localhost
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.userservice"

pdfservice:
  image: slidewiki/pdfservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=pdfservice.localhost
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.pdfservice"


fileservice:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.localhost
  volumes_from:
    - datapod
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.fileservice"

mongodb:
  image: mongo
  restart: on-failure:5
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    tag: "slidewiki.mongodb"
#  volumes:
#    - ./database:/data/db:rw

datapod:
  image: slidewiki/fileservice
  entrypoint: /bin/echo

logger:
  image: slidewiki/logger
  restart: on-failure:5
  ports:
    - "24224:24224"
  volumes:
    - /var/log/slidewiki:/fluentd/log
  privileged: true
