webserver:
  image: jwilder/nginx-proxy
  restart: on-failure:5
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro

platform:
  image: slidewiki/platform
#  build: /home/rmeissner/.git/slidewiki-platform/
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - PORT=80
    - VIRTUAL_HOST=platform.localhost
    - SERVICE_URL_DECK=http://deckservice
    - SERVICE_URL_DISCUSSION=http://discussionservice
    - SERVICE_URL_ACTIVITIES=http://activitiesservice
    - SERVICE_URL_NOTIFICATION=http://notificationservice
    - SERVICE_URL_USER=http://userservice
    - SERVICE_URL_IMPORT=http://importservice
    - SERVICE_URL_FILE=http://fileservice
    - SERVICE_VAR_IMPORT_HOST=importservice
  links:
    - notificationservice
    - deckservice
    - discussionservice
    - activitiesservice
    - userservice
    - importservice
    - fileservice

deckservice:
  image: slidewiki/deckservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.localhost

activitiesservice:
  image: slidewiki/activitiesservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=activitiesservice.localhost

discussionservice:
  image: slidewiki/discussionservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=discussionservice.localhost

notificationservice:
  image: slidewiki/notificationservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=notificationservice.localhost

importservice:
  image: slidewiki/importservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=importservice.localhost
  volumes:
    - ./images:/data/files/:rw

userservice:
  image: slidewiki/userservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=userservice.localhost

pdfservice:
  image: slidewiki/pdfservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=pdfservice.localhost

fileservice:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.localhost
  volumes:
    - ./images:/data/files:ro

mongodb:
  image: mongo
  restart: on-failure:5
  expose:
      - "27017"
  volumes:
    - ./database:/data/db:rw
