version: '2'

volumes:

  mongo-data: {}
  solr-data: {}
  files: {}
  certs: {}

services:

  # for production: Fluentd based logging
  logger:
    image: slidewiki/logger:latest
    restart: always
    volumes:
      - ${MAINTENANCE_DIR}/log:/fluentd/log
    expose:
      - "24224"
    privileged: true

  mongodb:
    volumes:
      - mongo-data:/data/db
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.mongodb"

  solr:
    volumes:
      - solr-data:/solr-data
    environment:
      - VIRTUAL_HOST=solr.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.solr"

  platform:
    environment:
      - VIRTUAL_HOST=${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=https://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=https://importservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=https://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_TAG=https://tagservice.${BASE_DOMAIN}
      - SERVICE_VAR_IMPORT_HOST=importservice.${BASE_DOMAIN}
      - SERVICE_PROTOCOL_IMPORT=https
      - SERVICE_PORT_IMPORT=443
      - SERVICE_USER_APIKEY=${APIKEY}
      - SERVICE_USER_PRIVATE_RECAPTCHA_KEY=${RECAPTCHA_PRIVATE_KEY}
      - SERVICE_USER_PUBLIC_RECAPTCHA_KEY=${RECAPTCHA_PUBLIC_KEY}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - SMTP_CLIENTNAME=${SMTP_CLIENTNAME}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.platform"

  deckservice:
    environment:
      - VIRTUAL_HOST=deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.deckservice"

  unoconvservice:
    restart: always
    environment:
      - VIRTUAL_HOST=unoconvservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.unoconv"

  activitiesservice:
    environment:
      - VIRTUAL_HOST=activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.activitiesservice"

  discussionservice:
    environment:
      - VIRTUAL_HOST=discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.discussionservice"

  notificationservice:
    environment:
      - VIRTUAL_HOST=notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.notificationservice"

  importservice:
    environment:
      - VIRTUAL_HOST=importservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_HOST_UNOCONV=unoconvservice.${BASE_DOMAIN}
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.importservice"

  userservice:
    environment:
      - VIRTUAL_HOST=userservice.${BASE_DOMAIN}
      - URL_PLATFORM=https://${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_CLIENTNAME=${SMTP_CLIENTNAME}
      - SMTP_ENABLED=${SMTP_ENABLED}
      - JWT_SERIAL=${JWT_SERIAL}
      - APIKEY=${APIKEY}
    volumes:
      - ./userservice/providerConfig.json:/nodeApp/config.json
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.userservice"

  pdfservice:
    environment:
      - VIRTUAL_HOST=pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_PLATFORM=https://${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.pdfservice"

  fileservice:
    environment:
      - VIRTUAL_HOST=fileservice.${BASE_DOMAIN}
    volumes:
      - files:/data/files
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.fileservice"

  searchservice:
    environment:
      - VIRTUAL_HOST=searchservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.searchservice"

  #xapi:
  #  environment:
  #    - VIRTUAL_HOST=xapiservice.${BASE_DOMAIN}
  #    - LETSENCRYPT_HOST=xapiservice.${BASE_DOMAIN}
  #    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  #    - LETSENCRYPT_TEST=true
  #  depends_on:
  #    - logger
  #  logging:
  #    driver: fluentd
  #    options:
  #      fluentd-address: "logger:24224"
  #      tag: "slidewiki.xapi"

  tagservice:
    environment:
      - VIRTUAL_HOST=tagservice.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=https://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=https://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_IMAGE=https://imageservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=https://importservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.tagservice"

  nlpstore:
    environment:
      - VIRTUAL_HOST=nlpstore.${BASE_DOMAIN}
      - SERVICE_URL_DECK=https://deckservice.${BASE_DOMAIN}
      - SERVICE_URL_DISCUSSION=https://discussionservice.${BASE_DOMAIN}
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.${BASE_DOMAIN}
      - SERVICE_URL_NOTIFICATION=https://notificationservice.${BASE_DOMAIN}
      - SERVICE_URL_USER=https://userservice.${BASE_DOMAIN}
      - SERVICE_URL_SEARCH=https://searchservice.${BASE_DOMAIN}
      - SERVICE_URL_IMAGE=https://imageservice.${BASE_DOMAIN}
      - SERVICE_URL_FILE=https://fileservice.${BASE_DOMAIN}
      - SERVICE_URL_PDF=https://pdfservice.${BASE_DOMAIN}
      - SERVICE_URL_IMPORT=https://importservice.${BASE_DOMAIN}
    depends_on:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: "logger:24224"
        tag: "slidewiki.nlpstore"
