version: '2'

networks:
  
  front-trier: {}
  back-trier: {}

services:

  mongodb:
    image: mongo:3.4
    container_name: mongodb
    expose:
        - "27017"
    networks:
      - back-trier
    volumes:
      - database:/data/db
    command: mongod --replSet "rs0"

  solr:
    image: slidewiki/solr:latest
    container_name: solr
    expose:
      - "8983"
    networks:
      - front-trier
      - back-trier
    depends_on:
      - mongodb

  webserver:
    image: slidewiki/webproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-trier
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd

  platform:
    image: slidewiki/platform:latest
    expose:
      - "80"
    environment:
      - PORT=80
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_DISCUSSION=https://discussionservice.testing.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.testing.slidewiki.org
      - SERVICE_URL_NOTIFICATION=https://notificationservice.testing.slidewiki.org
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
      - SERVICE_URL_IMPORT=https://importservice.testing.slidewiki.org
      - SERVICE_URL_FILE=https://fileservice.testing.slidewiki.org
      - SERVICE_URL_IMAGE=https://imageservice.stable.slidewiki.org
      - SERVICE_URL_SEARCH=https://searchservice.testing.slidewiki.org
      - SERVICE_URL_PDF=https://pdfservice.testing.slidewiki.org
      - SERVICE_URL_TAG=https://tagservice.testing.slidewiki.org
      - SERVICE_VAR_IMPORT_HOST=importservice.testing.slidewiki.org
      - SERVICE_PROTOCOL_IMPORT=https
      - SERVICE_PORT_IMPORT=443
    networks:
      - front-trier
    depends_on:
      - webserver
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - tagservice

  deckservice:
    image: slidewiki/deckservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_FILE=https://fileservice.testing.slidewiki.org
    depends_on:
      - fileservice
      - mongodb

  unoconvservice:
    image: zrrrzzt/docker-unoconv-webservice
    expose:
      - "3000"
    networks:
      - front-trier
      - back-trier


  activitiesservice:
    image: slidewiki/activitiesservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
    depends_on:
      - deckservice
      - userservice
      - mongodb

  discussionservice:
    image: slidewiki/discussionservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.testing.slidewiki.org
      - SERVICE_URL_NOTIFICATION=https://notificationservice.testing.slidewiki.org
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
    depends_on:
      - activitiesservice
      - notificationservice
      - userservice
      - mongodb

  notificationservice:
    image: slidewiki/notificationservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
    depends_on:
      - userservice
      - mongodb

  importservice:
    image: slidewiki/importservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_FILE=https://fileservice.testing.slidewiki.org
    depends_on:
      - deckservice
      - fileservice
      - mongodb

  userservice:
    image: slidewiki/userservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SMTP_PORT=25
      - SMTP_HOST=localhost
  #    - SMTP_FROM=me@hostername.org
  #    - SMTP_CLIENTNAME=
  #    - APIKey=
      - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
      - URL_PLATFORM=https://testing.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.testing.slidewiki.org
    volumes:
      - /data/userservice/providerConfig.json:/nodeApp/config.json
    depends_on:
  #    - platform
  #    - activitiesservice
      - mongodb

  pdfservice:
    image: slidewiki/pdfservice:latest
    expose:
      - "80"
    networks:
      - front-trier
    environment:
      - APPLICATION_PORT=80
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_PDF=https://pdfservice.testing.slidewiki.org
      - SERVICE_URL_PLATFORM=https://testing.slidewiki.org
    depends_on:
      - deckservice

  fileservice:
    image: slidewiki/fileservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  searchservice:
    image: slidewiki/searchservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
      - SOLR_HOST=solr
    depends_on:
      - userservice
      - solr
      - mongodb

  #xapi:
  #  image: slidewiki/xapi-service:latest
  #  expose:
  #    - "80"
  #  networks:
  #    - front-trier
  #  environment:
  #    - APPLICATION_PORT=80

  tagservice:
    image: slidewiki/tagservice:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_DISCUSSION=https://discussionservice.testing.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.testing.slidewiki.org
      - SERVICE_URL_NOTIFICATION=https://notificationservice.testing.slidewiki.org
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
      - SERVICE_URL_SEARCH=https://searchservice.testing.slidewiki.org
      - SERVICE_URL_IMAGE=https://imageservice.testing.slidewiki.org
      - SERVICE_URL_FILE=https://fileservice.testing.slidewiki.org
      - SERVICE_URL_PDF=https://pdfservice.testing.slidewiki.org
      - SERVICE_URL_IMPORT=https://importservice.testing.slidewiki.org
    depends_on:
      - mongodb

  nlpstore:
    image: slidewiki/nlpstore:latest
    expose:
      - "80"
    networks:
      - front-trier
      - back-trier
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.testing.slidewiki.org
      - SERVICE_URL_DISCUSSION=https://discussionservice.testing.slidewiki.org
      - SERVICE_URL_ACTIVITIES=https://activitiesservice.testing.slidewiki.org
      - SERVICE_URL_NOTIFICATION=https://notificationservice.testing.slidewiki.org
      - SERVICE_URL_USER=https://userservice.testing.slidewiki.org
      - SERVICE_URL_SEARCH=https://searchservice.testing.slidewiki.org
      - SERVICE_URL_IMAGE=https://imageservice.testing.slidewiki.org
      - SERVICE_URL_FILE=https://fileservice.testing.slidewiki.org
      - SERVICE_URL_PDF=https://pdfservice.testing.slidewiki.org
      - SERVICE_URL_IMPORT=https://importservice.testing.slidewiki.org
    depends_on:
      - mongodb
