webserver:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro

platform:
  image: slidewiki/platform
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - PORT=80
    - VIRTUAL_HOST=platform.manfredfris.ch
    - SERVICE_URL_DECK=http://deckservice.manfredfris.ch
    - SERVICE_URL_DISCUSSION=http://discussionservice.manfredfris.ch
    - SERVICE_URL_ACTIVITIES=http://activitiesservice.manfredfris.ch
    - SERVICE_URL_NOTIFICATION=http://notificationservice.manfredfris.ch
    - SERVICE_URL_USER=http://userservice.manfredfris.ch
    - SERVICE_URL_IMPORT=http://importservice.manfredfris.ch
    - SERVICE_URL_FILE=http://fileservice.manfredfris.ch
    - SERVICE_URL_SEARCH=http://searchservice.manfredfris.ch
    - SERVICE_VAR_IMPORT_HOST=importservice.manfredfris.ch

deckservice:
  image: slidewiki/deckservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.manfredfris.ch

activitiesservice:
  image: slidewiki/activitiesservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=activitiesservice.manfredfris.ch

discussionservice:
  image: slidewiki/discussionservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=discussionservice.manfredfris.ch

notificationservice:
  image: slidewiki/notificationservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=notificationservice.manfredfris.ch

importservice:
  image: slidewiki/importservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=importservice.manfredfris.ch
  volumes_from:
    - datapod:rw

userservice:
  image: slidewiki/userservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=userservice.manfredfris.ch

pdfservice:
  image: slidewiki/pdfservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=pdfservice.manfredfris.ch

fileservice:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.manfredfris.ch
  volumes_from:
    - datapod

searchservice:
  image: slidewiki/searchservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
    - solr
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=searchservice.manfredfris.ch
    - SERVICE_URL_USER=http://userservice..manfredfris.ch
    - SOLR_CORE=swikcore

solr:
  image: solr
  restart: on-failure:5
  expose:
   - "8983"
  volumes:
    - ./solrserver-config/solr-config:/opt/solr/server/solr:rw
  volumes_from:
    - datapod

mongodb:
  image: mongo
  restart: on-failure:5
  expose:
    - "27017"
  volumes_from:
    - datapod
  command: mongod --replSet "rs0"

datapod:
  image: mongo
  entrypoint: /bin/bash
  command: /bin/bash
  volumes:
    - /data/db
    - /data/files
    - /solr-data
