webserver:
  image: jwilder/nginx-proxy
  restart: on-failure:5
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
#    - ./certs:/etc/nginx/certs:ro
#    - /etc/nginx/vhost.d
#    - /usr/share/nginx/html

#letsencrypt:
#  image: jrcs/letsencrypt-nginx-proxy-companion
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock:ro
#    - ./certs:/etc/nginx/certs
#  volumes_from:
#    - webserver

platform:
  image: slidewiki/platform
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - PORT=80
    - VIRTUAL_HOST=platform.localhost

deckservice:
  image: slidewiki/deckservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - database
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.localhost

activitiesservice:
  image: slidewiki/activitiesservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - database
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=activitiesservice.localhost

discussionservice:
  image: slidewiki/discussionservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - database
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=discussionservice.localhost

notificationservice:
  image: slidewiki/notificationservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - database
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=notificationservice.localhost

importservice:
  image: slidewiki/importservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - database
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=importservice.localhost

database:
  image: mongo
  restart: on-failure:5
  volumes:
    - ./database:/data/db:rw
