version: '2'

services:

  mongodb:
    image: mongo:3.4
    restart: always
    expose:
      - "27017"
    command: mongod --replSet "rs0"

  solr:
    image: slidewiki/solr:${SLIDEWIKI_VERSION}
    restart: always
    environment:
      - VIRTUAL_PORT=8983
    expose:
      - "8983"
    depends_on:
      - mongodb

  platform:
    image: slidewiki/platform:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - PORT=80
    depends_on:
      - deckservice
      - activitiesservice
      - discussionservice
      - notificationservice
      - importservice
      - userservice
      - pdfservice
      - fileservice
      - searchservice
      - tagservice

  deckservice:
    image: slidewiki/deckservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SECRET_REVIEW_KEY=${SECRET_REVIEW_KEY}
    depends_on:
      - fileservice
      - mongodb

  unoconvservice:
    image: zrrrzzt/docker-unoconv-webservice
    restart: always
    environment:
      - VIRTUAL_PORT=3000
      - PAYLOAD_MAX_SIZE=314572800
    expose:
      - "3000"

  activitiesservice:
    image: slidewiki/activitiesservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - deckservice
      - notificationservice
      - userservice
      - mongodb

  discussionservice:
    image: slidewiki/discussionservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - deckservice
      - userservice
      - mongodb

  notificationservice:
    image: slidewiki/notificationservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - userservice
      - mongodb

  importservice:
    image: slidewiki/importservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_HOST_UNOCONV=unoconvservice.${BASE_DOMAIN}
    depends_on:
      - deckservice
      - fileservice
      - mongodb

  userservice:
    image: slidewiki/userservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SECRET_REVIEW_KEY=${SECRET_REVIEW_KEY}
    depends_on:
      - mongodb

  pdfservice:
    image: slidewiki/pdfservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
    depends_on:
      - deckservice

  fileservice:
    image: slidewiki/fileservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - APPLICATION_PATH=/data/files
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  searchservice:
    image: slidewiki/searchservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SOLR_CORE=swikcore
      - SOLR_HOST=solr
    depends_on:
      - userservice
      - solr
      - mongodb

  #xapi:
  #  image: slidewiki/xapi-service:${SLIDEWIKI_VERSION}
  #  restart: always
  #  expose:
  #    - "80"
  #  networks:
  #    - front-trier
  #  environment:
  #    - APPLICATION_PORT=80

  tagservice:
    image: slidewiki/tagservice:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb

  nlpstore:
    image: slidewiki/nlpstore:${SLIDEWIKI_VERSION}
    restart: always
    expose:
      - "80"
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb
