webserver:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro

platform:
  image: slidewiki/platform
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - PORT=80
    - VIRTUAL_HOST=platform.experimental.slidewiki.org
    - SERVICE_URL_DECK=http://deckservice.experimental.slidewiki.org
    - SERVICE_URL_DISCUSSION=http://discussionservice.experimental.slidewiki.org
    - SERVICE_URL_ACTIVITIES=http://activitiesservice.experimental.slidewiki.org
    - SERVICE_URL_NOTIFICATION=http://notificationservice.experimental.slidewiki.org
    - SERVICE_URL_USER=http://userservice.experimental.slidewiki.org
    - SERVICE_URL_IMPORT=http://importservice.experimental.slidewiki.org
    - SERVICE_URL_FILE=http://fileservice.experimental.slidewiki.org
    - SERVICE_URL_SEARCH=http://searchservice.experimental.slidewiki.org
    - SERVICE_VAR_IMPORT_HOST=importservice.experimental.slidewiki.org

deckservice:
  image: slidewiki/deckservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.experimental.slidewiki.org

activitiesservice:
  image: slidewiki/activitiesservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=activitiesservice.experimental.slidewiki.org

discussionservice:
  image: slidewiki/discussionservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=discussionservice.experimental.slidewiki.org

notificationservice:
  image: slidewiki/notificationservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=notificationservice.experimental.slidewiki.org

importservice:
  image: slidewiki/importservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=importservice.experimental.slidewiki.org
  volumes_from:
    - datapod:rw

userservice:
  image: slidewiki/userservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=userservice.experimental.slidewiki.org

pdfservice:
  image: slidewiki/pdfservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=pdfservice.experimental.slidewiki.org

fileservice:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.experimental.slidewiki.org
  volumes_from:
    - datapod

searchservice:
  image: slidewiki/searchservice
  restart: on-failure:5
  expose:
    - "80"
  links:
    - mongodb
    - solr
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=searchservice.experimental.slidewiki.org
    - SERVICE_URL_USER=http://userservice.experimental.slidewiki.org
    - SOLR_CORE=swikcore

solr:
  image: solr
  container_name: solr
  restart: always
#  expose:
#   - "8983"
  ports:
    - "8983:8983"
  volumes:
    - ./solrserver-config/solr-config:/opt/solr/server/solr:rw
  volumes_from:
    - datapod

mongodb:
  image: mongo
  container_name: mongodb
  restart: always
  expose:
    - "27017"
  volumes_from:
    - datapod
  command: mongod --replSet "rs0"

datapod:
  image: mongo
  container_name: datapod
  entrypoint: /bin/bash
  command: /bin/bash
  volumes:
    - /data/db
    - /data/files
    - /solr-data
